version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"

  app:
    build: .
    restart: unless-stopped
    container_name: "fastapi_app"
    volumes:
      - .:/messenger_app
    depends_on:
      - db
    ports:
      - "8000:8000"