"""empty message

Revision ID: 3a1d8e6ec2a6
Revises: dd8bc4548e81
Create Date: 2024-09-07 20:18:52.858550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1d8e6ec2a6'
down_revision: Union[str, None] = 'dd8bc4548e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('full_name', sa.String(), nullable=False))
    op.drop_column('applications', 'last_name')
    op.drop_column('applications', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('applications', 'full_name')
    # ### end Alembic commands ###
