"""empty message

Revision ID: d670c1893413
Revises: 
Create Date: 2024-10-09 15:32:36.071824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd670c1893413'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('important', sa.Boolean(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('requirements', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tasks', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('task', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vacancy_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('telegram', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('experience', sa.String(), nullable=False),
    sa.Column('portfolio', sa.String(), nullable=False),
    sa.Column('work_time', sa.String(), nullable=False),
    sa.Column('what_do_you_want', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CANCELED', 'VIEWED', 'APPROVED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_table('vacancies')
    # ### end Alembic commands ###
