"""empty message

Revision ID: dd8bc4548e81
Revises: 9cc92fa241db
Create Date: 2024-09-07 20:07:11.933757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8bc4548e81'
down_revision: Union[str, None] = '9cc92fa241db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('vacancies', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'status')
    op.drop_column('applications', 'created_at')
    # ### end Alembic commands ###
