"""empty message

Revision ID: e06b66cf2b87
Revises: 3a1d8e6ec2a6
Create Date: 2024-10-04 08:49:05.800574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06b66cf2b87'
down_revision: Union[str, None] = '3a1d8e6ec2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('answered_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'answered_at')
    # ### end Alembic commands ###
